### PR TITLE
Feature/attack variations

### PR DESCRIPTION
**Pull request by Jazy5552**
Haven't really implemented any specific variations, mostly set up a method to do so, that would work with the possession.

Ideally simply by switching the weapon gameobject within the Player object, would change the player's weapon. This is what the possession script will have to do. I'm going to continue to work on this, but feel free to review it, test it, and let me know what you think.

Also this may break some sandboxes, sorry.

### CODE REVIEW

**Comment by Jazy5552** [comment]
So the way I handled the projectiles going through walls and stuff is that I made it so they destroy when colliding with something tagged as "Wall". This means they will go through enemies and players (Unless they destroy the projectile when it hits them of course), so friendly fire is not a thing. This also means that Alek's walls need to be tagged appropriately, I didn't do this because I won't want to cause merge conflicts with the wall prefabs and stuff.

**Comment by AleksandrHovhannisyan** [comment]
Be sure to pull develop :)

**Comment by AleksandrHovhannisyan** [comment]
It looks like the enemies never take damage because BasicProjectile is tagged as Enemy-Fireball, and both the player and enemies use that projectile. So the player takes damage, but the enemies don't.

**Comment by Jazy5552** [comment]
**It looks like the enemies never take damage because BasicProjectile is tagged as Enemy-Fireball**
The tag doesn't actually matter, because the weapon controllers are explicitly setting the tag of the projectile at runtime. Reason I did this is so that we wouldn't have to use 2 different projectile prefabs (1 for the player and 1 for the enemy). Also this works in my sandbox scene which is what I was testing in (We can integrate everything later into the other scenes)

**It's also too easy to strafe the enemies and avoid their fire**
Yeah I was just playing around with the enemy movement script. We don't have to use that, nor do I suggest we do.

**doors don't open in my scene**
That sounds like (assuming you are still using the collision detection method) an issue with collision detection and the way CCPlayer is rigged (or the room).

**Pull request merged**
